# **Importing libraries**

In [1]:
import numpy as np
import torch

# **Creating 1D, 2D, and 3D Tensors**

In [2]:
# -------- NumPy --------
np_1d = np.array([1, 2, 3])
np_2d = np.array([[1, 2], [3, 4]])
np_3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print("NumPy 1D:\n", np_1d)
print("NumPy 2D:\n", np_2d)
print("NumPy 3D:\n", np_3d)

# -------- PyTorch --------
torch_1d = torch.tensor([1, 2, 3])
torch_2d = torch.tensor([[1, 2], [3, 4]])
torch_3d = torch.tensor([[[1, 2], [3, 4]],
                          [[5, 6], [7, 8]]])

print("\nPyTorch 1D:\n", torch_1d)
print("PyTorch 2D:\n", torch_2d)
print("PyTorch 3D:\n", torch_3d)


NumPy 1D:
 [1 2 3]
NumPy 2D:
 [[1 2]
 [3 4]]
NumPy 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

PyTorch 1D:
 tensor([1, 2, 3])
PyTorch 2D:
 tensor([[1, 2],
        [3, 4]])
PyTorch 3D:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


# **Element-wise Operations**

In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])


# **Dot Product & Matrix Multiplication**

In [4]:
# Dot product (1D vectors)
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])

dot_product = torch.dot(v1, v2)
print("Dot Product:", dot_product)

# Matrix multiplication
m1 = torch.tensor([[1, 2],
                   [3, 4]])
m2 = torch.tensor([[5, 6],
                   [7, 8]])

matmul_result = torch.matmul(m1, m2)
print("Matrix Multiplication:\n", matmul_result)


Dot Product: tensor(32)
Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])


# **Indexing, Slicing & Boolean Masking**

In [5]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Indexing
print("Element at (0,1):", x[0, 1])

# Slicing
print("First two rows:\n", x[:2])

# Extracting subtensor
print("Subtensor:\n", x[1:, 1:])

# Boolean Masking
mask = x > 5
print("Boolean Mask:\n", mask)
print("Elements > 5:", x[mask])


Element at (0,1): tensor(2)
First two rows:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Subtensor:
 tensor([[5, 6],
        [8, 9]])
Boolean Mask:
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
Elements > 5: tensor([6, 7, 8, 9])


# **Reshaping Tensors (view, reshape, unsqueeze, squeeze)**

In [7]:
t = torch.tensor([1, 2, 3, 4])

# view()
print("View (2x2):\n", t.view(2, 2))

# reshape()
print("Reshape (2x2):\n", t.reshape(2, 2))

# unsqueeze (add dimension)
t_unsq = t.unsqueeze(0)
print("Unsqueeze (dim=0):", t_unsq.shape)

# squeeze (remove dimension)
t_sq = t_unsq.squeeze()
print("Squeeze:", t_sq.shape)


View (2x2):
 tensor([[1, 2],
        [3, 4]])
Reshape (2x2):
 tensor([[1, 2],
        [3, 4]])
Unsqueeze (dim=0): torch.Size([1, 4])
Squeeze: torch.Size([4])


**Comparison with NumPy reshape**

In [8]:
np_t = np.array([1, 2, 3, 4])
print("NumPy reshape:\n", np_t.reshape(2, 2))


NumPy reshape:
 [[1 2]
 [3 4]]


# **Broadcasting**

In [9]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
B = torch.tensor([10, 20, 30])

# Broadcasting automatically expands B
print("Broadcasting Result:\n", A + B)


Broadcasting Result:
 tensor([[11, 22, 33],
        [14, 25, 36]])


# **In-place vs Out-of-place Operations**

In [10]:
x = torch.tensor([1, 2, 3])

# Out-of-place
y = x + 5
print("Out-of-place:")
print("x:", x)
print("y:", y)

# In-place
x.add_(5)
print("\nIn-place:")
print("x after add_:", x)


Out-of-place:
x: tensor([1, 2, 3])
y: tensor([6, 7, 8])

In-place:
x after add_: tensor([6, 7, 8])
